# Generated by Django 4.1.3 on 2022-11-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsocore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicado')], default=0),
        ),
    ]
