# Generated by Django 4.1.3 on 2022-11-16 03:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funsocore', '0002_alter_post_options_rename_author_post_autor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Publicacion',
        ),
    ]
