# Generated by Django 4.1.3 on 2022-12-06 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsocore', '0004_post_delete_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='post',
            name='occurr_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
